version: '3.8'

services:
  backend:
    build: ./backend  # Point to the backend folder where the Dockerfile is located
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    volumes:
      - ./backend:/app # Mount backend directory for live code updates
    env_file: "./backend/.env"  # Use the .env file inside backend
    restart: always  # Restart container if it crashes

  frontend:
    build: ./frontend  # Point to the frontend folder where the Dockerfile is located
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    volumes:
      - ./frontend:/app # Mount frontend directory for live code updates
      - /app/node_modules
    env_file: "./frontend/.env"
    restart: always  # Restart container if it crashes