name: 👶 Subtask Issue
description: Create a structured subtask issue with clear description and acceptance criteria.
title: "[Subtask] <Brief Description>"
labels: ["subtask"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief overview of what this subtask involves.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        List the acceptance criteria for this subtask. Use `- [ ]` to create checkboxes.
      placeholder: |
        - [ ] Implement feature according to specifications.
        - [ ] Ensure code follows project guidelines.
        - [ ] Write unit/integration tests.
        - [ ] Verify no breaking changes are introduced.
    validations:
      required: true
