name: Run Pytest on PR

on:
  pull_request:
    branches:
      - main  # Change this to match your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Set your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Adjust if needed

      - name: Run Pytest
        run: pytest --maxfail=5 --disable-warnings  # Modify flags as needed
